apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wikijs
  name: wikijs
  namespace: wikijs
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: wikijs
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wikijs
    spec:
      containers:
      - env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: postgres-config
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT
              name: postgres-config
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: postgres-config
        - name: DB_TYPE
          valueFrom:
            configMapKeyRef:
              key: DB_TYPE
              name: postgres-config
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: postgres-config
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres
        image: requarks/wiki:2
        imagePullPolicy: IfNotPresent
        name: wikijs
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30