apiVersion: v1
data:
  DB_HOST: "10.100.252.221"
  DB_PORT: "5432"
  DB_USER: "postgresadmin"
  DB_TYPE: "postgres"
  DB_NAME: "wikijs-demo"
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: wikijs